const stories = {
  princess: {theme:'Magical Kingdom',title:'The Princess and the Moon Door',scene:['🌙','🏰','👸🏾'],start:'Princess Amara discovered a mysterious silver door glowing beneath the castle stairs. A tiny dragon whispered, “The moonlight is waiting for someone courageous.”',choices:[{label:'🌲 Follow the moonlit path',text:'Amara stepped through and followed a shimmering path into an enchanted forest. The branches hummed a gentle song and pointed towards a sleepy giant.'},{label:'🗝️ Turn the golden key',text:'Amara turned the ancient key. The whole castle floated into the clouds, where a curious moon fox needed her help finding its family.'}]},
  sport: {theme:'Sporting Heroes',title:'The Last-Minute Goal',scene:['🏟️','⚽','🧑🏾'],start:'Kai heard a thunderous cheer as the championship match began. His enormous team badge sparkled beneath the spectacular stadium lights.',choices:[{label:'⚽ Try the clever pass',text:'Kai spotted a surprising gap and made an extraordinary pass. His teammate raced forward while the crowd counted down.'},{label:'🏃 Dribble towards goal',text:'Kai moved carefully around the final defender. With one courageous kick, the ball curved towards the top corner.'}]},
  space: {theme:'Space Explorers',title:"Milo's Mission to Mars",scene:['🪐','🚀','🧑🏽‍🚀'],start:"Milo fastened his enormous space helmet and checked the rocket's flashing controls. A surprising signal was bouncing all the way from Mars.",choices:[{label:'📡 Answer the signal',text:'Milo answered carefully. A friendly robot appeared on screen and invited him to an extraordinary zero-gravity race.'},{label:'🚀 Blast towards Mars',text:'The rocket zoomed through a spectacular meteor shower. Milo spotted a hidden station sparkling beneath the red dust.'}]},
  dinosaur: {theme:'Dinosaur Island',title:'The Secret Jungle Egg',scene:['🌋','🥚','🦖'],start:'Zuri pushed through the gigantic ferns and found an unusual rainbow egg. Nearby, a gentle dinosaur made a thunderous worried sound.',choices:[{label:'🥚 Protect the egg',text:'Zuri built a shelter from enormous leaves. Soon the egg cracked and a magnificent baby dinosaur peeped out.'},{label:'🔎 Search for its family',text:'Zuri followed some mysterious footprints across the island and discovered a peaceful valley full of dinosaurs.'}]}
};

Object.assign(stories.princess,{
  pages:[
    'The sleepy giant opened one eye. He had lost the silver bell that guided travellers safely through the forest. Amara promised that she and the tiny dragon would help him find it.',
    'They followed a trail of moon-shaped flowers to a rushing river. Amara listened carefully and heard a faint ringing beneath an old wooden bridge. The dragon lit the dark space with a warm golden flame.',
    'Amara found the bell caught between two stones. When she returned it, the giant smiled and rang it once. A bridge of moonlight carried everyone home, and Amara knew that courage and kindness made the greatest magic.'
  ],
  questions:[
    {text:'What was glowing beneath the castle stairs?',answer:'A silver door',options:['A silver door','A golden crown','A green boat']},
    {text:'Who whispered to Amara?',answer:'A tiny dragon',options:['A tiny dragon','A moon fox','A sleepy giant']},
    {text:'What had the giant lost?',answer:'A silver bell',options:['A silver bell','A castle key','A red scarf']},
    {text:'Where was the bell caught?',answer:'Between two stones',options:['Between two stones','Inside the castle','High in a tree']},
    {text:'What helped Amara make the greatest magic?',answer:'Courage and kindness',options:['Courage and kindness','Running very fast','Owning lots of gold']}
  ]
});
Object.assign(stories.sport,{
  pages:[
    'The ball reached Kai again as the final minute began. His teammates called to one another and spread across the pitch. Kai remembered that a strong team watches, listens, and works together.',
    'A defender blocked the goal, so Kai looked up instead of rushing. He saw his teammate Ava in a clear space and sent the ball towards her. Ava controlled it and passed it straight back.',
    'Kai struck the ball just before the whistle. It flew into the net and the stadium erupted with cheers. Kai thanked his teammates because every pass had helped to create the winning goal.'
  ],
  questions:[
    {text:'What kind of match was Kai playing?',answer:'A championship match',options:['A championship match','A tennis match','A practice race']},
    {text:'What sparkled beneath the stadium lights?',answer:'His team badge',options:['His team badge','His shoes','The whistle']},
    {text:'What does a strong team do?',answer:'Watches, listens and works together',options:['Watches, listens and works together','Keeps the ball alone','Stops speaking']},
    {text:'Who did Kai pass to near the end?',answer:'Ava',options:['Ava','Milo','Amara']},
    {text:'Why did Kai thank his teammates?',answer:'Every pass helped make the goal',options:['Every pass helped make the goal','They bought him a prize','They changed the rules']}
  ]
});
Object.assign(stories.space,{
  pages:[
    'The signal showed Milo a map of a hidden station near Mars. He checked his fuel, fastened his safety belt, and guided the rocket towards a blinking blue light.',
    'Inside the station, Milo met a friendly robot called Beep. A meteor had damaged the station antenna, so messages could not reach home. Milo used his toolkit while Beep held the light.',
    'Together they repaired the antenna and sent a clear signal across space. The station crew cheered, and Milo recorded the discovery in his logbook before beginning the long journey home.'
  ],
  questions:[
    {text:'Where was the surprising signal coming from?',answer:'Mars',options:['Mars','The Moon','Earth']},
    {text:'What did the signal show Milo?',answer:'A map of a hidden station',options:['A map of a hidden station','A football score','A dinosaur egg']},
    {text:'What was the robot called?',answer:'Beep',options:['Beep','Ava','Spark']},
    {text:'What had damaged the antenna?',answer:'A meteor',options:['A meteor','A dragon','Heavy rain']},
    {text:'Where did Milo record the discovery?',answer:'In his logbook',options:['In his logbook','On the wall','Inside his helmet']}
  ]
});
Object.assign(stories.dinosaur,{
  pages:[
    'The worried dinosaur was the egg’s mother. Zuri noticed that smoke was rising beyond the trees, and the ground gave a small rumble. They needed to move somewhere safe before the volcano woke.',
    'Zuri led the dinosaurs towards a peaceful valley beside a wide blue lake. The smallest dinosaurs became tired, so everyone slowed down and stayed together until the whole herd arrived.',
    'The rainbow egg cracked beneath a shady tree, and a baby dinosaur peeped out. Its mother gave a joyful call. Zuri watched the family settle safely in the valley and promised to visit again.'
  ],
  questions:[
    {text:'What did Zuri find among the ferns?',answer:'A rainbow egg',options:['A rainbow egg','A silver bell','A space helmet']},
    {text:'Who did the worried dinosaur turn out to be?',answer:"The egg's mother",options:["The egg's mother",'A friendly robot','A football coach']},
    {text:'Why did everyone need to move?',answer:'The volcano might wake',options:['The volcano might wake','It was bedtime','The lake was empty']},
    {text:'Where did Zuri lead the dinosaurs?',answer:'A peaceful valley',options:['A peaceful valley','A busy stadium','A dark castle']},
    {text:'Why did the herd slow down?',answer:'The smallest dinosaurs were tired',options:['The smallest dinosaurs were tired','They lost the egg','It began to snow']}
  ]
});

stories.princess.extraChoices=[
  {prompt:'How should Amara wake the sleepy giant?',options:[{label:'🎵 Sing the forest song',effect:'Amara sang the gentle forest song. The giant woke with a peaceful smile and listened to her story.'},{label:'🐉 Ask the dragon to help',effect:'The tiny dragon gave a friendly squeak. The giant opened one eye and leaned closer to listen.'}]},
  {prompt:'Which way should they search for the bell?',options:[{label:'🌸 Follow the moon flowers',effect:'Amara followed the glowing moon flowers, which grew brighter whenever she chose the correct path.'},{label:'👂 Listen for its ringing',effect:'Everyone stood completely still. Amara heard a soft ringing and carefully led them towards it.'}]},
  {prompt:'How should Amara reach beneath the bridge?',options:[{label:'🔥 Use the dragon’s light',effect:'The dragon made a warm golden flame, revealing a safe path beneath the bridge.'},{label:'🪵 Build a stepping path',effect:'Amara placed strong pieces of wood across the shallow water and stepped carefully towards the sound.'}]}
];
stories.sport.extraChoices=[
  {prompt:'What should Kai tell his team?',options:[{label:'🤝 “Let’s work together!”',effect:'Kai reminded everyone to work together. The team spread out and called clearly to one another.'},{label:'💪 “Keep believing!”',effect:'Kai encouraged his teammates to keep believing. They lifted their heads and raced back into position.'}]},
  {prompt:'How should Kai get past the defender?',options:[{label:'👀 Look for a teammate',effect:'Kai looked across the pitch and spotted Ava moving into a clear space.'},{label:'⚡ Change direction quickly',effect:'Kai changed direction quickly, creating just enough space to look up and plan the next pass.'}]},
  {prompt:'What should Kai do before the final shot?',options:[{label:'⚽ Pass to Ava and move',effect:'Kai passed to Ava and sprinted into space. She returned the ball at exactly the right moment.'},{label:'📣 Call out the plan',effect:'Kai called out the plan so his teammates knew where to move. Together they opened a path towards goal.'}]}
];
stories.space.extraChoices=[
  {prompt:'How should Milo approach the hidden station?',options:[{label:'🐢 Fly slowly and carefully',effect:'Milo reduced the rocket’s speed and checked every flashing control before moving closer.'},{label:'📡 Send a friendly message',effect:'Milo sent a friendly greeting. A blue light blinked twice, inviting him towards the station.'}]},
  {prompt:'Who should repair the damaged antenna?',options:[{label:'🧰 Milo uses the toolkit',effect:'Milo opened his toolkit and selected the correct tools while Beep studied the instructions.'},{label:'🤖 Milo and Beep work together',effect:'Milo and Beep made a plan together, sharing the tools and checking each other’s work.'}]},
  {prompt:'How should they test the antenna?',options:[{label:'🌍 Send a message to Earth',effect:'They sent a short message towards Earth and waited as the signal travelled across space.'},{label:'✨ Follow the blinking lights',effect:'They followed the blinking lights along the antenna, checking every section until all of them glowed green.'}]}
];
stories.dinosaur.extraChoices=[
  {prompt:'How should Zuri warn the dinosaur herd?',options:[{label:'📣 Make a loud warning call',effect:'Zuri copied the mother dinosaur’s warning call. Heads rose above the ferns as the herd listened.'},{label:'👣 Show them the smoky trail',effect:'Zuri pointed towards the smoky sky and showed the herd a safe trail away from the volcano.'}]},
  {prompt:'Which route should the herd take?',options:[{label:'🌊 Follow the river',effect:'Zuri followed the river because its cool water led away from the smoky mountain.'},{label:'🦋 Follow the butterflies',effect:'A cloud of bright butterflies fluttered towards the valley, and Zuri carefully followed them.'}]},
  {prompt:'How should everyone help the tired little dinosaurs?',options:[{label:'🛑 Stop for a short rest',effect:'The herd rested beneath the trees until the smallest dinosaurs were ready to continue.'},{label:'🤝 Walk slowly together',effect:'The larger dinosaurs walked beside the smallest ones, and the whole herd moved at a gentle pace.'}]}
];

const phonics={mysterious:'mys–TEER–ee–us',courageous:'kuh–RAY–jus',shimmering:'SHIM–er–ing',enchanted:'en–CHAN–tid',ancient:'AYN–shunt',curious:'KYOOR–ee–us',enormous:'ih–NOR–mus',surprising:'ser–PRY–zing',extraordinary:'ik–STROR–din–air–ee',spectacular:'spek–TAK–yuh–ler',gigantic:'jy–GAN–tik',unusual:'un–YOO–zhoo–ul',thunderous:'THUN–der–us',magnificent:'mag–NIF–ih–sunt',discovered:'dis–KUV–erd',carefully:'KAIR–fuh–lee',peaceful:'PEES–ful',championship:'CHAM–pee–un–ship',defender:'dee–FEN–der'};
Object.assign(phonics,{
  a:'uh',all:'awl',an:'an',amara:'uh–MAR–uh',and:'and',answered:'AN–serd',appeared:'uh–PEERD',around:'uh–ROUND',as:'az',baby:'BAY–bee',badge:'baj',ball:'bawl',began:'buh–GAN',beneath:'buh–NEETH',bouncing:'BOWN–sing',branches:'BRAN–chiz',built:'bilt',castle:'KAS–ul',checked:'chekt',cheer:'cheer',clouds:'klowdz',controls:'kun–TROHLZ',corner:'KOR–ner',counted:'KOWN–tid',crowd:'krowd',cracked:'krakt',curved:'kurvd',dinosaur:'DYE–nuh–sor',dinosaurs:'DYE–nuh–sorz',door:'dor',down:'down',dragon:'DRAG–un',dust:'dust',egg:'eg',family:'FAM–uh–lee',fastened:'FAS–und',ferns:'furnz',final:'FYE–nul',finding:'FYN–ding',flashing:'FLASH–ing',floated:'FLOH–tid',followed:'FOL–ohd',footprints:'FOOT–prints',for:'for',forward:'FOR–werd',found:'fownd',fox:'foks',friendly:'FREND–lee',from:'from',gap:'gap',gentle:'JEN–tul',giant:'JYE–unt',glowing:'GLOH–ing',gravity:'GRAV–uh–tee',heard:'hurd',helmet:'HEL–mit',help:'help',her:'hur',hidden:'HID–un',him:'him',his:'hiz',hummed:'humd',into:'IN–too',invited:'in–VYE–tid',is:'iz',island:'EYE–lund',its:'its',kai:'kye',key:'kee',kick:'kik',leaves:'leevz',lights:'lyts',made:'mayd',mars:'marz',match:'mach',meteor:'MEE–tee–or',milo:'MY–loh',moon:'moon',moonlight:'MOON–lyt',moved:'moovd',nearby:'NEER–bye',needed:'NEE–did',on:'on',one:'wun',out:'owt',pass:'pas',path:'path',peeped:'peept',pointed:'POYN–tid',princess:'PRIN–sess',pushed:'poosht',race:'rays',raced:'rayst',rainbow:'RAYN–boh',red:'red',robot:'ROH–bot',rocket:'ROK–it',rockets:'ROK–its',screen:'skreen',shelter:'SHEL–ter',shower:'SHOW–er',signal:'SIG–nul',silver:'SIL–ver',sleepy:'SLEE–pee',someone:'SUM–wun',song:'song',soon:'soon',sound:'sownd',space:'spays',sparkled:'SPAR–kuld',sparkling:'SPAR–kling',spotted:'SPOT–id',stairs:'stairz',station:'STAY–shun',stepped:'stept',stadium:'STAY–dee–um',team:'teem',teammate:'TEEM–mayt',the:'thuh',through:'throo',tiny:'TY–nee',to:'too',top:'top',towards:'tuh–WORDZ',turned:'turnd',valley:'VAL–ee',waiting:'WAY–ting',was:'woz',way:'way',where:'wair',while:'wyle',whispered:'WIS–perd',whole:'hohl',with:'with',worried:'WUR–eed',zero:'ZEER–oh',zoomed:'zoomd',zuri:'ZOO–ree'
});
function dateKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
const today=dateKey();const yesterdayDate=new Date();yesterdayDate.setDate(yesterdayDate.getDate()-1);const yesterday=dateKey(yesterdayDate);
const storedDay=localStorage.getItem('meehee-reading-day');
const storedGameDay=localStorage.getItem('meehee-game-day');
const savedRewards=JSON.parse(localStorage.getItem('meehee-rewards')||'[]').map(reward=>typeof reward==='string'?{name:reward,cost:100}:reward);
const lastCompleted=localStorage.getItem('meehee-last-goal-date')||'';const savedStreak=Number(localStorage.getItem('meehee-streak')||0);
const state={
  stars:Number(localStorage.getItem('meehee-stars')||120), words:JSON.parse(localStorage.getItem('meehee-words')||'[]'),
  stories:Number(localStorage.getItem('meehee-stories')||0), seconds:storedDay===today?Number(localStorage.getItem('meehee-reading-seconds')||0):0,
  rewarded:storedDay===today&&localStorage.getItem('meehee-mission-rewarded')==='yes', rewards:savedRewards,
  hiddenRewards:JSON.parse(localStorage.getItem('meehee-hidden-rewards')||'[]'),
  gameStars:storedGameDay===today?Number(localStorage.getItem('meehee-game-stars')||0):0,
  streak:lastCompleted===today||lastCompleted===yesterday?savedStreak:0,lastCompleted,
  profile:localStorage.getItem('meehee-profile')||'princess', current:null
};
const storyModal=document.querySelector('#story-modal'),panelModal=document.querySelector('#panel-modal'),storyText=document.querySelector('#story-text'),choices=document.querySelector('#choice-area');let storyRun=null;

function formatTime(seconds){const mins=Math.floor(seconds/60);return `${mins}:${String(seconds%60).padStart(2,'0')}`}
function updateTimer(){
  document.querySelector('#reading-time').textContent=`${formatTime(state.seconds)} of 10:00`;
  document.querySelector('#mission-progress').style.width=`${Math.min(100,state.seconds/6)}%`;
  if(state.seconds>=600&&!state.rewarded){state.stars+=30;state.rewarded=true;completeDailyGoal();save()}
}
function completeDailyGoal(){if(state.lastCompleted===today)return;state.streak=state.lastCompleted===yesterday?state.streak+1:1;state.lastCompleted=today}
function save(){
  localStorage.setItem('meehee-stars',state.stars);localStorage.setItem('meehee-words',JSON.stringify(state.words));localStorage.setItem('meehee-stories',state.stories);
  localStorage.setItem('meehee-reading-day',today);localStorage.setItem('meehee-reading-seconds',state.seconds);localStorage.setItem('meehee-mission-rewarded',state.rewarded?'yes':'no');
  localStorage.setItem('meehee-rewards',JSON.stringify(state.rewards));localStorage.setItem('meehee-hidden-rewards',JSON.stringify(state.hiddenRewards));localStorage.setItem('meehee-profile',state.profile);localStorage.setItem('meehee-streak',state.streak);localStorage.setItem('meehee-last-goal-date',state.lastCompleted);
  localStorage.setItem('meehee-game-day',today);localStorage.setItem('meehee-game-stars',state.gameStars);
  document.querySelector('#star-count').textContent=state.stars;document.querySelector('#reader-stars').textContent=state.stars;document.querySelector('#word-summary').textContent=`${state.words.length} word${state.words.length===1?'':'s'} saved`;updateTimer();
  document.querySelector('#streak-count').textContent=state.streak;
  document.querySelector('#game-stars').textContent=state.gameStars;
}

setInterval(()=>{if(!storyModal.hidden&&!document.hidden){state.seconds+=1;updateTimer();if(state.seconds%5===0)save()}},1000);
window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});
function openModal(modal){modal.hidden=false;document.body.classList.add('modal-open')}
function closeModals(){save();storyModal.hidden=true;panelModal.hidden=true;document.body.classList.remove('modal-open')}
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',closeModals));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModals()}));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});

function getPhonics(word){if(phonics[word])return phonics[word];const chunks=word.match(/[^aeiouy]*[aeiouy]+(?:[^aeiouy](?=[^aeiouy]|$))?|[^aeiouy]+/g);return chunks?.join('–')||word}
function wordify(text){return text.split(/(\s+)/).map(part=>{const clean=part.toLowerCase().replace(/[^a-z]/g,'');return clean?`<button class="word ${state.words.includes(clean)?'learned':''}" data-word="${clean}" aria-label="Hear and save ${clean}">${part}</button>`:part}).join('')}
function bindWords(){storyText.querySelectorAll('.word').forEach(button=>button.addEventListener('click',()=>helpWord(button.dataset.word,button)))}
function speak(word,slow=false){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const voice=new SpeechSynthesisUtterance(word);voice.rate=slow?.55:.82;voice.pitch=1.05;speechSynthesis.speak(voice)}
function helpWord(word,button){if(!state.words.includes(word)){state.words.push(word);button.classList.add('learned');state.stars+=2;save()}document.querySelector('.phonics-pop')?.remove();const pop=document.createElement('div');pop.className='phonics-pop';pop.innerHTML=`<span>🔊</span><div><small>Sound it out</small><br><strong>${getPhonics(word)}</strong></div><button>Hear “${word}” slowly</button>`;pop.querySelector('button').addEventListener('click',()=>speak(word,true));storyText.after(pop);speak(word)}
function pageLabel(page){document.querySelector('#story-theme').textContent=`${stories[state.current].theme} · Page ${page} of 5`}
function openStory(key){const story=stories[key];state.current=key;storyRun={page:1,choice:null,nextIntro:'',answers:[],score:0};document.querySelector('#story-title').textContent=story.title;document.querySelector('#story-scene').innerHTML=story.scene.map(x=>`<span aria-hidden="true">${x}</span>`).join('');renderStoryPage();openModal(storyModal)}
function renderStoryPage(){const story=stories[state.current],page=storyRun.page;pageLabel(page);document.querySelector('.phonics-pop')?.remove();const mainText=page===1?story.start:page===2?story.choices[storyRun.choice].text:story.pages[page-3],text=storyRun.nextIntro?`${storyRun.nextIntro} ${mainText}`:mainText;storyRun.nextIntro='';storyText.innerHTML=wordify(text);bindWords();if(page===1){choices.innerHTML=`<p>What should happen next?</p>${story.choices.map((c,i)=>`<button class="choice" data-choice="${i}">${c.label}</button>`).join('')}`;choices.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>{storyRun.choice=Number(b.dataset.choice);storyRun.page=2;renderStoryPage()}));return}if(page<5){const decision=story.extraChoices[page-2];choices.innerHTML=`<p>${decision.prompt}</p>${decision.options.map((option,i)=>`<button class="choice" data-next-choice="${i}">${option.label}</button>`).join('')}`;choices.querySelectorAll('[data-next-choice]').forEach(button=>button.addEventListener('click',()=>{storyRun.nextIntro=decision.options[Number(button.dataset.nextChoice)].effect;storyRun.page++;renderStoryPage()}));return}choices.innerHTML='<p>You finished the story. Now show what you remember!</p><button class="choice finish" id="story-next">Answer 5 questions 🧠</button>';document.querySelector('#story-next').addEventListener('click',startStoryQuestions)}
function startStoryQuestions(){storyRun.answers=[];storyRun.score=0;renderStoryQuestion(0)}
function renderStoryQuestion(index){const story=stories[state.current],question=story.questions[index],mixedAnswers=shuffle(question.options);document.querySelector('#story-theme').textContent=`Memory check · Question ${index+1} of 5`;storyText.innerHTML=`<strong>${question.text}</strong>`;choices.innerHTML=`<button class="choice finish" id="hear-question">🔊 Read question aloud</button>${mixedAnswers.map(option=>`<button class="choice" data-answer="${option.replaceAll('"','&quot;')}">${option}</button>`).join('')}<p id="question-feedback" aria-live="polite"></p>`;document.querySelector('#hear-question').addEventListener('click',()=>speak(question.text,true));choices.querySelectorAll('[data-answer]').forEach(button=>button.addEventListener('click',()=>answerStoryQuestion(index,button.dataset.answer)))}
function answerStoryQuestion(index,answer){const question=stories[state.current].questions[index],correct=answer===question.answer;if(correct)storyRun.score++;storyRun.answers.push(answer);choices.querySelectorAll('button').forEach(button=>button.disabled=true);document.querySelector('#question-feedback').textContent=correct?'Correct! Brilliant remembering. ⭐':`Good try. The answer was “${question.answer}”.`;setTimeout(()=>index<4?renderStoryQuestion(index+1):finishStoryQuestions(),900)}
function finishStoryQuestions(){if(storyRun.score>=4){storyText.innerHTML=`<strong>Fantastic! You scored ${storyRun.score} out of 5.</strong>`;choices.innerHTML='<p>You remembered the story and earned your reward.</p><button class="choice finish" id="collect-story-stars">Collect 20 stars ⭐</button>';document.querySelector('#collect-story-stars').addEventListener('click',finishStory)}else{storyText.innerHTML=`<strong>You scored ${storyRun.score} out of 5.</strong>`;choices.innerHTML='<p>You need 4 correct answers. Read the story again, then have another try — you can do it!</p><button class="choice finish" id="reread-story">Read the story again 📖</button>';document.querySelector('#reread-story').addEventListener('click',()=>{storyRun={page:1,choice:null,nextIntro:'',answers:[],score:0};renderStoryPage()})}}
function finishStory(){state.stars+=20;state.stories+=1;save();closeModals();showPanel('words')}
document.querySelectorAll('.story-card').forEach(card=>card.querySelector('button').addEventListener('click',()=>openStory(card.dataset.story)));document.querySelector('#start-story').addEventListener('click',()=>document.querySelector('.stories').scrollIntoView({behavior:'smooth'}));

function applyProfile(profile){
  state.profile=profile;const sport=profile==='sport';document.body.classList.toggle('sport-mode',sport);
  document.querySelector('.avatar').textContent=sport?'⚽':'ME';document.querySelector('#hero-icon').textContent=sport?'⚽':'🏰';
  document.querySelector('#hero-eyebrow').textContent=sport?'Your next sporting adventure':'Your next reading adventure';
  document.querySelector('#hero-title').innerHTML=sport?'Ready to <span>read, play and score?</span>':'Where will your <span>imagination</span> take you?';
  document.querySelector('#hero-description').textContent=sport?'Choose a challenge, tap tricky words for help, and make choices that lead your team to victory.':'Choose a story, tap tricky words for help, and make choices that change what happens next.';
  const card=document.querySelector('#featured-story');card.dataset.story=sport?'sport':'princess';document.querySelector('#featured-emoji').textContent=sport?'⚽🏃🏾':'👸🏾';document.querySelector('#featured-theme').textContent=sport?'Sporting Heroes':'Magical Kingdom';document.querySelector('#featured-title').textContent=sport?'The Last-Minute Goal':'The Princess and the Moon Door';save();
}

function profileChooser(){return `<div class="profile-choice"><button class="profile-option ${state.profile==='princess'?'selected':''}" data-profile="princess"><span>👧🏾</span>Girl adventures<small>Magic and princess stories</small></button><button class="profile-option ${state.profile==='sport'?'selected':''}" data-profile="sport"><span>⚽</span>Boy adventures<small>Sport and team challenges</small></button></div>`}
function bindProfileButtons(){document.querySelectorAll('[data-profile]').forEach(button=>button.addEventListener('click',()=>{applyProfile(button.dataset.profile);showPanel('parents')}))}
function verifyParent(){const entered=window.prompt('Grown-up password:');if(entered===null)return false;if(entered!=='Parent'){window.alert('That password is not correct. Please ask a grown-up.');return false}return true}
function removeWord(word){if(!verifyParent())return;state.words=state.words.filter(saved=>saved!==word);save();showPanel('words')}
function removeReward(kind,id){if(!verifyParent())return;if(kind==='built-in')state.hiddenRewards.push(id);else state.rewards.splice(Number(id),1);save();showPanel('rewards')}
function redeemReward(name,cost){if(!verifyParent())return;if(state.stars<cost){window.alert('There are not enough stars for this reward yet.');return}if(!window.confirm(`Approve “${name}” for ${cost} stars?`))return;state.stars-=cost;save();showPanel('rewards');window.alert(`${name} approved! ${cost} stars have been used.`)}
function showPanel(type){
  const panel=document.querySelector('#panel-content');
  if(type==='words'){
    panel.innerHTML=`<p class="eyebrow">Your reading toolkit</p><h2 id="panel-title">My tricky words</h2><p class="panel-intro">Tap a word to hear it again. Removing words needs the grown-up password.</p>${state.words.length?`<div class="word-list">${state.words.map(w=>`<div class="saved-word"><span>🔤</span><div><strong>${w}</strong><small>${getPhonics(w)}</small></div><div class="row-actions"><button data-speak="${w}">🔊 Hear</button><button class="remove-button" data-remove-word="${w}">Remove</button></div></div>`).join('')}</div>`:'<div class="empty-state">📖<br>Tap any word inside a story and it will appear here.</div>'}`;panel.querySelectorAll('[data-speak]').forEach(b=>b.addEventListener('click',()=>speak(b.dataset.speak,true)));panel.querySelectorAll('[data-remove-word]').forEach(b=>b.addEventListener('click',()=>removeWord(b.dataset.removeWord)));
  }else if(type==='rewards'){
    const builtIns=[{id:'treat',icon:'🍬',name:'A shop treat',cost:80},{id:'money',icon:'💰',name:'Pocket money bonus',cost:150},{id:'film',icon:'🎬',name:'Choose family film',cost:200}].filter(r=>!state.hiddenRewards.includes(r.id));
    const rewards=[...builtIns.map(r=>({...r,kind:'built-in'})),...state.rewards.map((r,index)=>({id:String(index),icon:'🎁',name:r.name,cost:r.cost,kind:'custom'}))];panel.innerHTML=`<p class="eyebrow">Stars become smiles</p><h2 id="panel-title">My rewards</h2><p class="panel-intro">You have <strong>${state.stars} stars</strong>. Approval and removal both need the grown-up password.</p><div class="reward-list">${rewards.map(r=>`<div class="reward-row"><span>${r.icon}</span><div><strong>${r.name}</strong><small>${r.cost} stars</small></div><div class="row-actions"><button class="claim-button" data-claim="${r.id}" ${state.stars<r.cost?'disabled':''}>${state.stars>=r.cost?'Ask grown-up':'Keep reading'}</button><button class="remove-button" data-remove-reward="${r.id}" data-kind="${r.kind}">Remove</button></div></div>`).join('')}</div>`;
    panel.querySelectorAll('[data-claim]').forEach(button=>{const reward=rewards.find(r=>r.id===button.dataset.claim);button.addEventListener('click',()=>redeemReward(reward.name,reward.cost))});panel.querySelectorAll('[data-remove-reward]').forEach(button=>button.addEventListener('click',()=>removeReward(button.dataset.kind,button.dataset.removeReward)));
  }else{
    panel.innerHTML=`<p class="eyebrow">Choose your style</p><h2 id="panel-title">My profile</h2><p class="panel-intro">Pick the kind of reading world you would like to see.</p>${profileChooser()}<p class="eyebrow">Grown-up view</p><h2>MeeHee's progress</h2><div class="parent-code"><small>Progress proof code</small><strong>ME-${state.stories+24}R</strong><small>Changes as stories are completed</small></div><div class="stat-grid"><div class="stat"><strong>${state.stories}</strong><small>stories finished</small></div><div class="stat"><strong>${formatTime(state.seconds)}</strong><small>reading today</small></div><div class="stat"><strong>${state.words.length}</strong><small>words practised</small></div></div><p class="timer-note">Reading time counts only while a story is open and visible. A 10-minute day keeps the streak going.</p><label class="form-label" for="reward-name">Add a family reward</label><form class="custom-reward"><input id="reward-name" required maxlength="40" aria-label="Custom reward" placeholder="e.g. Choose Friday's dinner"><input class="reward-cost" required type="number" min="1" max="9999" step="1" aria-label="Stars needed" placeholder="Stars needed"><button>Add reward</button></form><small class="reward-help">Choose any value from 1 to 9,999 stars.</small>`;bindProfileButtons();panel.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const name=e.currentTarget.querySelector('#reward-name').value.trim();const cost=Number(e.currentTarget.querySelector('.reward-cost').value);if(!name||!Number.isInteger(cost)||cost<1||cost>9999)return;state.rewards.push({name,cost});save();showPanel('rewards')});
  }openModal(panelModal)
}
const gameInfo={ninja:['🥷','Word Ninja'],sounds:['🏁','Sound-It-Out Race'],treasure:['🗺️','Word Treasure Hunt'],sentence:['🧩','Sentence Builder'],rhyme:['🫧','Rhyme Time'],missing:['🔎','Missing Word Mystery'],memory:['🃏','Tricky Word Match'],rescue:['🦸🏾','Story Rescue'],spell:['🚀','Spell Blaster'],silly:['🤪','Silly Story Studio']};
let gameSession=null;
const fallbackWords=['mysterious','courageous','enormous','surprising','spectacular','gigantic'];
function shuffle(items){return [...items].sort(()=>Math.random()-.5)}
function gameWords(){return [...new Set([...state.words,...fallbackWords])].slice(0,6)}
function gameHeader(key,instructions){const [icon,title]=gameInfo[key];return `<div class="game-stage"><div class="game-icon">${icon}</div><p class="eyebrow">Games Arcade</p><h2 id="panel-title">${title}</h2><p class="panel-intro">${instructions}</p><div class="game-hud"><span>⭐ Score: <b id="round-score">${gameSession?.score||0}</b></span><span>🎮 Today: ${state.gameStars}/30</span></div><div id="game-board"></div></div>`}
function awardGameStars(points){const earned=Math.max(0,Math.min(points,10,30-state.gameStars));state.gameStars+=earned;state.stars+=earned;save();return earned}
function finishGame(message='Great reading practice!'){const earned=awardGameStars(gameSession.score);document.querySelector('#game-board').innerHTML=`<div class="game-finish">🎉<strong>+${earned} stars</strong><p>${message}</p><small>${state.gameStars}/30 game stars earned today</small><br><button class="game-next" data-play-again>Play again</button></div>`;document.querySelector('[data-play-again]').addEventListener('click',()=>startGame(gameSession.key))}
function startQuiz(key,instructions,questions,speakTarget=false){gameSession={key,score:0,round:0,questions:shuffle(questions).slice(0,5)};const panel=document.querySelector('#panel-content');panel.innerHTML=gameHeader(key,instructions);openModal(panelModal);renderQuizRound(speakTarget)}
function renderQuizRound(speakTarget=false){if(gameSession.round>=gameSession.questions.length){finishGame();return}const q=gameSession.questions[gameSession.round];const board=document.querySelector('#game-board');board.innerHTML=`<p class="game-prompt">${q.prompt}</p><div class="game-options">${shuffle(q.options).map(option=>`<button class="game-option" data-answer="${option.replaceAll('"','&quot;')}">${option}</button>`).join('')}</div><div class="game-feedback"></div>`;if(speakTarget)speak(q.target||q.answer);board.querySelectorAll('[data-answer]').forEach(button=>button.addEventListener('click',()=>{const correct=button.dataset.answer===q.answer;button.classList.add(correct?'correct':'wrong');board.querySelectorAll('[data-answer]').forEach(b=>b.disabled=true);if(correct)gameSession.score+=2;document.querySelector('#round-score').textContent=gameSession.score;board.querySelector('.game-feedback').textContent=correct?'Brilliant! +2 ⭐':`Good try — the answer was “${q.answer}”.`;setTimeout(()=>{gameSession.round++;renderQuizRound(speakTarget)},850)}))}

function ninjaGame(){const words=gameWords();const questions=words.map(word=>({prompt:'Tap the word you hear 🔊',target:word,answer:word,options:shuffle([word,...shuffle(words.filter(w=>w!==word)).slice(0,2)])}));startQuiz('ninja','Listen carefully and catch the right word before it escapes!',questions,true)}
function soundGame(){const words=gameWords();const questions=words.map(word=>({prompt:`Which sound pattern builds <strong>${word}</strong>?`,answer:getPhonics(word),options:shuffle([getPhonics(word),word.slice(0,2)+'–'+word.slice(2),word.split('').reverse().join('–')])}));startQuiz('sounds','Choose the phonics sounds that build each word.',questions)}
function treasureGame(){startQuiz('treasure','Follow each sound clue to uncover the treasure!',[{prompt:'Find something beginning with “ch”',answer:'🪑 chair',options:['🪑 chair','🍎 apple','🌙 moon','🐸 frog']},{prompt:'Find something beginning with “sh”',answer:'👟 shoe',options:['👟 shoe','🐱 cat','🚲 bike','🍰 cake']},{prompt:'Find something ending with “ck”',answer:'🦆 duck',options:['🦆 duck','🌳 tree','🐝 bee','🐟 fish']},{prompt:'Find something beginning with “b”',answer:'⚽ ball',options:['⚽ ball','☀️ sun','🧀 cheese','🦊 fox']},{prompt:'Find something beginning with “r”',answer:'🚀 rocket',options:['🚀 rocket','👑 crown','⭐ star','🐶 dog']}])}
function rhymeGame(){startQuiz('rhyme','Pop the word that rhymes with the clue!',[{prompt:'What rhymes with <strong>cat</strong>?',answer:'hat',options:['hat','dog','sun','fish']},{prompt:'What rhymes with <strong>moon</strong>?',answer:'spoon',options:['spoon','star','book','cake']},{prompt:'What rhymes with <strong>play</strong>?',answer:'day',options:['day','ball','tree','ship']},{prompt:'What rhymes with <strong>light</strong>?',answer:'kite',options:['kite','cloud','door','fox']},{prompt:'What rhymes with <strong>read</strong>?',answer:'seed',options:['seed','page','word','look']}])}
function missingGame(){startQuiz('missing','Use the sentence clues to find the missing word.',[{prompt:'The dinosaur hid behind the enormous ___.',answer:'tree',options:['tree','spoon','sock','moon']},{prompt:'The rocket blasted into ___.',answer:'space',options:['space','puddle','kitchen','pillow']},{prompt:'The goalkeeper caught the ___.',answer:'ball',options:['ball','book','cake','boat']},{prompt:'The princess opened the silver ___.',answer:'door',options:['door','shoe','cloud','fish']},{prompt:'We use our eyes to ___ a book.',answer:'read',options:['read','bounce','taste','kick']}])}
function rescueGame(){startQuiz('rescue','Every correct answer helps your hero cross the bridge!',[{prompt:'The bridge is shaking! Choose the word meaning very big.',answer:'enormous',options:['enormous','tiny','quiet','slow']},{prompt:'A dragon blocks the path. Choose the bravest word.',answer:'courageous',options:['courageous','sleepy','little','soft']},{prompt:'The key is hidden. Which word means not ordinary?',answer:'unusual',options:['unusual','normal','plain','same']},{prompt:'The door sparkles brightly. Which word means amazing to see?',answer:'spectacular',options:['spectacular','dull','empty','silent']},{prompt:'You saved the story! Which word means calm and quiet?',answer:'peaceful',options:['peaceful','noisy','angry','rough']}])}

function sentenceGame(){const rounds=[['The','friendly','dragon','waved.'],['Milo','flew','to','Mars.'],['Kai','kicked','the','ball.']];gameSession={key:'sentence',score:0,round:0,rounds};const panel=document.querySelector('#panel-content');panel.innerHTML=gameHeader('sentence','Tap the word cards in the correct order.');openModal(panelModal);renderSentence()}
function renderSentence(){if(gameSession.round>=gameSession.rounds.length){finishGame('Your sentences make perfect sense!');return}const answer=gameSession.rounds[gameSession.round];let built=[];const board=document.querySelector('#game-board');board.innerHTML=`<p class="game-prompt">Build the sentence</p><div class="built-word" id="built-sentence">Tap words below…</div><div class="letter-tray">${shuffle(answer).map((word,index)=>`<button class="letter-button" data-word="${word}" data-index="${index}">${word}</button>`).join('')}</div><button class="game-next" id="check-sentence">Check sentence</button><div class="game-feedback"></div>`;board.querySelectorAll('[data-word]').forEach(b=>b.addEventListener('click',()=>{built.push(b.dataset.word);b.disabled=true;document.querySelector('#built-sentence').textContent=built.join(' ')}));document.querySelector('#check-sentence').addEventListener('click',()=>{const correct=built.join(' ')===answer.join(' ');if(correct)gameSession.score+=3;board.querySelector('.game-feedback').textContent=correct?'Perfect sentence! ⭐':`Almost! It was: ${answer.join(' ')}`;document.querySelector('#round-score').textContent=gameSession.score;setTimeout(()=>{gameSession.round++;renderSentence()},900)})}

function spellGame(){gameSession={key:'spell',score:0,round:0,rounds:shuffle(gameWords()).slice(0,3)};const panel=document.querySelector('#panel-content');panel.innerHTML=gameHeader('spell','Listen, then blast the letters into the correct order.');openModal(panelModal);renderSpell()}
function renderSpell(){if(gameSession.round>=gameSession.rounds.length){finishGame('Fantastic spelling blast!');return}const word=gameSession.rounds[gameSession.round];let built='';const board=document.querySelector('#game-board');board.innerHTML=`<p class="game-prompt">Spell the word you hear <button class="game-next" id="hear-spell">🔊 Hear</button></p><div class="built-word" id="spell-built">_</div><div class="letter-tray">${shuffle(word.split('')).map((letter,index)=>`<button class="letter-button" data-letter="${letter}" data-index="${index}">${letter}</button>`).join('')}</div><button class="game-next" id="check-spell">Fire! 🚀</button><div class="game-feedback"></div>`;speak(word);document.querySelector('#hear-spell').addEventListener('click',()=>speak(word,true));board.querySelectorAll('[data-letter]').forEach(b=>b.addEventListener('click',()=>{built+=b.dataset.letter;b.disabled=true;document.querySelector('#spell-built').textContent=built}));document.querySelector('#check-spell').addEventListener('click',()=>{const correct=built===word;if(correct)gameSession.score+=3;board.querySelector('.game-feedback').textContent=correct?'Direct hit! ⭐':`The word was ${word}.`;document.querySelector('#round-score').textContent=gameSession.score;setTimeout(()=>{gameSession.round++;renderSpell()},900)})}

function memoryGame(){const words=gameWords().slice(0,3);const cards=shuffle(words.flatMap(word=>[{id:word,label:word},{id:word,label:'🔊 '+getPhonics(word)}]));gameSession={key:'memory',score:0,first:null,matched:0};const panel=document.querySelector('#panel-content');panel.innerHTML=gameHeader('memory','Match each tricky word with its sound pattern.');openModal(panelModal);const board=document.querySelector('#game-board');board.innerHTML=`<div class="memory-grid">${cards.map((card,index)=>`<button class="memory-card" data-card="${index}" data-id="${card.id}" data-label="${card.label}">?</button>`).join('')}</div><div class="game-feedback"></div>`;board.querySelectorAll('[data-card]').forEach(button=>button.addEventListener('click',()=>flipMemory(button)))}
function flipMemory(button){if(button.classList.contains('revealed')||button.classList.contains('matched'))return;button.classList.add('revealed');button.textContent=button.dataset.label;if(!gameSession.first){gameSession.first=button;return}const first=gameSession.first;gameSession.first=null;if(first.dataset.id===button.dataset.id){first.classList.add('matched');button.classList.add('matched');gameSession.matched++;gameSession.score+=3;document.querySelector('#round-score').textContent=gameSession.score;if(gameSession.matched===3)setTimeout(()=>finishGame('Memory master! You matched every pair.'),600)}else{setTimeout(()=>{[first,button].forEach(b=>{b.classList.remove('revealed');b.textContent='?'})},700)}}

function sillyGame(){gameSession={key:'silly',score:5};const panel=document.querySelector('#panel-content');panel.innerHTML=gameHeader('silly','Choose three ingredients and create a hilarious story.');openModal(panelModal);const board=document.querySelector('#game-board');board.innerHTML=`<div class="game-options"><label>Hero<select id="silly-hero"><option>enormous hamster</option><option>football-playing dragon</option><option>dancing astronaut</option></select></label><label>Action<select id="silly-action"><option>juggled jelly</option><option>flew backwards</option><option>sang to the moon</option></select></label><label>Place<select id="silly-place"><option>inside a castle</option><option>at the stadium</option><option>on Dinosaur Island</option></select></label></div><button class="game-next" id="make-story">Make my story!</button><div id="silly-result"></div>`;document.querySelector('#make-story').addEventListener('click',()=>{const hero=document.querySelector('#silly-hero').value,action=document.querySelector('#silly-action').value,place=document.querySelector('#silly-place').value;document.querySelector('#silly-result').innerHTML=`<p class="story-result">Once upon a time, an ${hero} ${action} ${place}. Everyone laughed so loudly that a surprised moon fox fell off its chair!</p><button class="game-next" id="finish-silly">I read my silly story!</button>`;document.querySelector('#finish-silly').addEventListener('click',()=>finishGame('Wonderful! Make another and read it aloud.'))})}

function startGame(key){({ninja:ninjaGame,sounds:soundGame,treasure:treasureGame,sentence:sentenceGame,rhyme:rhymeGame,missing:missingGame,memory:memoryGame,rescue:rescueGame,spell:spellGame,silly:sillyGame})[key]()}
document.querySelectorAll('[data-game]').forEach(button=>button.addEventListener('click',()=>startGame(button.dataset.game)));
document.querySelectorAll('[data-open]').forEach(button=>button.addEventListener('click',()=>showPanel(button.dataset.open)));document.querySelector('.avatar').addEventListener('click',()=>showPanel('parents'));applyProfile(state.profile);

